#!/usr/bin/env bash
# Author Bereket Dereje
# Configures an Nginx server to listen on port 80.
# fix nginx listening on port 80
# Go to sites-enabled folder for Nginx
# Delete the default file
# Create symbolic link to the deafult file in sites-available

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default
/etc/nginx/sites-enabled/default
service nginx restart
