#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
# Author Bereket Dereje
# Sets nginx for listening to 80 port

sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
