#!/usr/bin/env bash
# Author Bereket Dereje Mekonnen
# This script displays all active IPv4 addresses
#  IPs on the machine it’s executed on.

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
